### ISSUE TITLE
geom_help.py Runtime warning 

### ISSUE THREAD

**Issue by gsclara** [tudelft3d/cjio#15]
While trying to export a file (attached here) from .json to .obj, I got the following warning: 
RuntimeWarning: invalid value encountered in true_divide
  n = n / sqrt(n[0]*n[0] + n[1]*n[1] + n[2]*n[2])
[helsinki_lod1.json.zip](https://github.com/tudelft3d/cjio/files/3321180/helsinki_lod1.json.zip)

**Comment by hugoledoux** [comment]
the very large coordinates were the main problem.

0.5.5 adds a translate() operator, which solves this issue
