### ISSUE TITLE
convert to obj

### ISSUE THREAD

**Issue by onikolskyy** [tudelft3d/cjio#16]
Hello guys,

thanks very much for the cjio tool!

I have pip3-installed it and would like to convert some cityjson.
However the cjio cli tool seems to not be callable from shell. But I can import cjio as a module in my python script. Is there some docs how to use it for the conversion?

[I'm using ubuntu 18.04 ]

Thanks very much in advance!

**Comment by hugoledoux** [comment]
please provide the error you get went just typing `cjio` in the console

**Comment by onikolskyy** [comment]
command not found: cjio

**Comment by balazsdukai** [comment]
It looks like that the installation didn't succeed. I'm under ubuntu 18.04 as and just did this:

```sh
pipenv --python 3.6
pipenv shell
pip install cjio
cjio
```

You can substitute pipenv with any virtual environment, but if you don't use one, then probably you'll need `pip install --user`.
