### ISSUE TITLE
export to obj compressed

### ISSUE THREAD

**Issue by BrendaXx** [tudelft3d/cjio#17]
I am trying to convert some CityJSON files to obj, but the output I get looks like a compressed obj file:

[test.txt](https://github.com/tudelft3d/cjio/files/3590476/test.txt)
![111](https://user-images.githubusercontent.com/16100293/64529813-034da800-d30c-11e9-845b-8fb97399a716.JPG)

Should the file be automatically compressed in the conversion? When I put decompress before the export function, the output looks good
![222](https://user-images.githubusercontent.com/16100293/64530077-91299300-d30c-11e9-8cd2-a72d5b0c478d.JPG)

**Comment by hugoledoux** [comment]
cheers for reporting, it's fixed (5284b91ecf8ed278cd7605b808d04c98fcc6749d)

It's in the 'develop' branch now, will be in next release. 

In the meantime, you can just use it like this:
```
pip install git+https://github.com/tudelft3d/cjio@develop
```
