### ISSUE TITLE
BOM issues

### ISSUE THREAD

**Issue by Athelena** [tudelft3d/cjio#21]
Some software quietly adds a BOM to a file. While this is illegal in the JSON specs, the truth is it still happens a lot with JSON files. The consequence here is it causes cjio to crash. I got the error: 

> Error: Unexpected UTF-8 BOM (decode using utf-8-sig): line 1 column 1 (char 0) 

Perhaps, it's better to flag it as an issue but not to crash? That's what the R library jsonlite does for example, it ignores the BOM and warns but continues.

**Comment by hugoledoux** [comment]
We didn't code an explicit crash, obviously...

Send me one file please? It's with the standard json library, should be documented

**Comment by hugoledoux** [comment]
baf169a2a283cae4bf9f9b9e26ff83b51646ff7e
