### ISSUE TITLE
Output of merge

### ISSUE THREAD

**Issue by Athelena** [tudelft3d/cjio#26]
When running merge you always get the info of the first file. So in this case:

`cjio random10_1.json merge random10_2.json info`

the result is:
```
{
  "cityjson_version": "1.0",
  ...
  "cityobjects_total": 10,
  ...
}
{
  "cityjson_version": "1.0",
 ...
  "cityobjects_total": 20,
  ...
}
```
and in this case:

`cjio random10_1.json merge random10_2.json save merged.json`

the result is:
```
{
  "cityjson_version": "1.0",
  ...
  "cityobjects_total": 10,
  ...
}
```
So my question is whether there is any point in having the info of the first file in the output? In the first case it looks messy and redundant and in the second case it makes it look like the merge was unsuccessful, which was not the case.

**Comment by hugoledoux** [comment]
Which branch? I remember fixing that a while ago in 'develop'.

I'd say it's safe to use develop in every day use at this point:
```
pip install git+https://github.com/tudelft3d/cjio@develop
```

**Comment by Athelena** [comment]
Ahh sorry, I checked issues for it but forgot to check develop.
