### ISSUE TITLE
CityJSON.validate() complains about vertices as tuples

### ISSUE THREAD

**Issue by balazsdukai** [tudelft3d/cjio#32]
The API casts the coordinates to tuples, not lists. Tuples should be allowed as they are bit more efficient on the memory.
```
(False,
 False,
 ["(0.0, 0.0, 0.0) is not of type 'array'",
  "(0.0, 0.0, 10.0) is not of type 'array'",
  "(0.0, 10.0, 0.0) is not of type 'array'",
  "(0.0, 10.0, 10.0) is not of type 'array'",
  "(10.0, 0.0, 0.0) is not of type 'array'",
  "(10.0, 0.0, 10.0) is not of type 'array'",
  "(10.0, 10.0, 0.0) is not of type 'array'",
  "(10.0, 10.0, 10.0) is not of type 'array'"],
 [])
```

**Comment by hugoledoux** [comment]
But () is not valid JSON, only dict {} and arrays []

**Comment by balazsdukai** [comment]
As long as its a python object, it doesn't matter, the `json` library takes care of converting the python data types to JSON data types. Both python lists and tuples-s are converted to arrays by `json.dump()`.

However, using tuples does make a difference over lists. In case of Dutch coordinates (somewhere in Delft), it makes 16 bytes difference per vertex.

```python
import sys
sys.getsizeof([84945.726,447458.018,0.52])
Out[3]: 88
sys.getsizeof((84945.726,447458.018,0.52))
Out[4]: 72
```

I don't see a reason why `validate` should complain about a tuple not being an array, since it is validating the deserialised JSON anyway, thus we don't have `JSON array / object` anymore, but python data types.

**Comment by hugoledoux** [comment]
but this is not cjio, this is jsonschema validation that throws that error, we just pass it to the user.

**Comment by balazsdukai** [comment]
Ok, then this is different issue. Closing this one.
